### ISSUE TITLE
Reorganise meta.ini and update README

### ISSUE THREAD

**Issue by EnAppelsin** [EnAppelsin/SHARCarRandomiser#31]
'Dev' has now reorganised the meta.ini settings into pages - but before release I propose a few cleanups:

1. Don't have groups if the page is entirely 1 group
2. Move gameplay/misc into one page (with 2 groups) or onto first tab.
3. Change the default setting width/height to better show all the options?
4. Possibly have the/a setting which enables the random stat variables on the same page so you know what disables/enables. (This may require more thought). 

Any other suggestions for changes to the meta.ini can be made here to keep track of for a bit.

**Comment by Hampo** [comment]
Oh nice, cheers Jake. You should actually be on there too from your early commits

**Comment by Hampo** [comment]
With the updated documentation (http://docs.donutteam.com/books/lucas-simpsons-hit-run-mod-launcher/page/about-mods), for number 4 we can put a label setting at the top of the random stats variables page

**Comment by duckdotapk** [comment]
```
[Author]
Name=Jake 
Credits=1
Group=Contributing

[Author]
Name=Loren
Credits=1
Group=Contributing
```

To be consistent with how Jake and I usually list ourselves in our mods, we should probably be listed as `Jake "AerHx" Andreøli` and `Loren "Duck" Goodwin`. Otherwise, this will result in us being listed multiple times in the Mod Launcher's authors list that refer to us in the Mod Launcher's [author category](https://dl.dropboxusercontent.com/s/8tdn9zang4kpqbu/Lucas%20Simpsons%20Hit%20%26%20Run%20Mod%20Launcher_2018-07-06_04-29-41.png).

Something to keep in mind if you make this change is that the ø in Jake's name requires the file to be encoded in UTF-8-BOM.

**Comment by EnAppelsin** [comment]
The readme has been updated and meta.ini has been updated with all the changes so far. I am closing this issue as it is believed both are now up to date and ready for a release.
